version: "3.1"

services:
  base_postgres:
    image: postgres:16.1
    container_name: project_postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 9000:5432
    networks:
      - postgres

networks:
  postgres:
    name: bridge-mock-shop
    driver: bridge

volumes:
  postgres:
  pgadmin:
